name: Sentry Release
description: Create a Sentry release from a Buildkite pipeline
author: https://github.com/jradtilbrook
requirements:
  - bash
configuration:
  properties:
    auth_token_env:
      type: string
    environment:
      type: string
    org:
      type: string
    project:
      type: string
    source-maps-artifact:
      type: string
  required:
    - org
    - project
  additionalProperties: false
