#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"

SENTRY_ORG=$(plugin_read_config ORG "")
if [ -z "${SENTRY_ORG}" ]; then
  echo 'Missing "org" option in the plugin'
  exit 1
fi
SENTRY_PROJECT=$(plugin_read_config PROJECT "")
if [ -z "${SENTRY_ORG}" ]; then
  echo 'Missing "project" option in the plugin'
  exit 1
fi

token_env=$(plugin_read_config AUTH_TOKEN_ENV "SENTRY_AUTH_TOKEN")
SENTRY_AUTH_TOKEN=${!token_env}
SENTRY_ENVIRONMENT=$(plugin_read_config ENVIRONMENT "production")
SOURCE_MAPS=$(plugin_read_config SOURCE_MAPS "")

SENTRY_CLI_VERSION="2.37.0"
echo "Downloading Sentry CLI version"
curl -sL https://sentry.io/get-cli/ | env SENTRY_CLI_VERSION INSTALL_DIR=/tmp/sentry sh
SENTRY_BIN=/tmp/sentry/sentry

echo "Creating and configuring sentry release for: $BUILDKITE_COMMIT"
$SENTRY_BIN releases new $BUILDKITE_COMMIT
echo "Setting commits for: $BUILDKITE_COMMIT"
$SENTRY_BIN releases set-commits --auto $BUILDKITE_COMMIT
echo "Adding a deploy for: $SENTRY_ENVIRONMENT"
$SENTRY_BIN releases deploys new -e $SENTRY_ENVIRONMENT -r $BUILDKITE_COMMIT

if [[ -n "${SOURCE_MAPS}" ]]; then
  echo "Downloading source map artifacts from ${SOURCE_MAPS}"
  mkdir "source-maps-{$BUILDKITE_BUILD_ID}"
  buildkite-agent artifact download "$SOURCE_MAPS" "source-maps-{$BUILDKITE_BUILD_ID}"
  echo "Uploading source maps to release"
  $SENTRY_BIN sourcemaps upload -r $BUILDKITE_COMMIT "source-maps-{$BUILDKITE_BUILD_ID}"
fi

echo "Finalising release: $BUILDKITE_COMMIT"
$SENTRY_BIN releases finalize $BUILDKITE_COMMIT
